// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFF6yO1_aAHEE1WBFNToOLejWW5zpkdOw',
    appId: '1:65374733669:web:1eff4074bf4e8ad4ec8d8c',
    messagingSenderId: '65374733669',
    projectId: 'my-todo-51f04',
    authDomain: 'my-todo-51f04.firebaseapp.com',
    storageBucket: 'my-todo-51f04.appspot.com',
    measurementId: 'G-97THBXC3XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hhLcKH6vU9v2KV7jh2Il28MPyRhDt4w',
    appId: '1:65374733669:android:70d20cf06c547f87ec8d8c',
    messagingSenderId: '65374733669',
    projectId: 'my-todo-51f04',
    storageBucket: 'my-todo-51f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6UsQWpiRQsYgPZ4AZLh5cjmuh95TknJM',
    appId: '1:65374733669:ios:7df3a461b4566db2ec8d8c',
    messagingSenderId: '65374733669',
    projectId: 'my-todo-51f04',
    storageBucket: 'my-todo-51f04.appspot.com',
    iosClientId: '65374733669-h7r1c7v0mdnkf9kg6lp2k2ung8miq3uq.apps.googleusercontent.com',
    iosBundleId: 'com.fasila.mytodo.myTodo',
  );
}
